#!/bin/bash -xe
## Quick'n'dirtay tests. Use git to ensure no undesired diffs on the greenbar.
cd $(dirname $0)
cleancd() { rm -rf $1; mkdir $1 && cd $1; }
cleancd greenbar
for n in ../input/*.*; do
    (
        cleancd $(basename $n)
        ../../../bin/zu ../$n >1 2>2 || cat 1 2
    )
done
ls -l *
